services:
  field:
    build: .
    ports:
      - "80:3000"
    volumes:
      - ./data:/app/data
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    command: sh -c "npm run build && npm run start"
    restart: always
